# Generated by Django 5.0.1 on 2024-01-28 10:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pantry_min', models.IntegerField(blank=True, null=True)),
                ('pantry_max', models.IntegerField(blank=True, null=True)),
                ('refrigerate_min', models.IntegerField(blank=True, null=True)),
                ('refrigerate_max', models.IntegerField(blank=True, null=True)),
                ('freeze_min', models.IntegerField(blank=True, null=True)),
                ('freeze_max', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStoredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('purchase_date', models.DateField(default=datetime.date.today)),
                ('shelf_life_min', models.IntegerField(blank=True, null=True)),
                ('shelf_life_max', models.IntegerField(blank=True, null=True)),
                ('storage_method', models.CharField(choices=[('refrigerate', 'Refrigerate'), ('freeze', 'Freeze'), ('pantry', 'Pantry')], default='refrigerate', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
